<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'norsys_seo.translated_tag_builder' shared service.

return $this->services['norsys_seo.translated_tag_builder'] = new \Norsys\SeoBundle\Services\TagBuilder\TranslatedTagBuilder(${($_ = isset($this->services['norsys_seo.tag_builder']) ? $this->services['norsys_seo.tag_builder'] : $this->services['norsys_seo.tag_builder'] = new \Norsys\SeoBundle\Services\TagBuilder\TagBuilder()) && false ?: '_'}, ${($_ = isset($this->services['norsys_seo.configurable_translator']) ? $this->services['norsys_seo.configurable_translator'] : $this->load('getNorsysSeo_ConfigurableTranslatorService.php')) && false ?: '_'});
