<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'norsys_seo.configurable_translator' shared service.

return $this->services['norsys_seo.configurable_translator'] = new \Norsys\SeoBundle\Services\Translator\ConfigurableTranslator(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, true, 'seo');
