<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'norsys_seo.twig.extension.seo' shared service.

$this->services['norsys_seo.twig.extension.seo'] = $instance = new \Norsys\SeoBundle\Twig\Extension\SeoExtension($this->parameters['norsys.seo.metas'], $this->parameters['norsys.seo.title'], $this->parameters['norsys.seo.links'], ${($_ = isset($this->services['norsys_seo.translated_tag_builder']) ? $this->services['norsys_seo.translated_tag_builder'] : $this->load('getNorsysSeo_TranslatedTagBuilderService.php')) && false ?: '_'});

$instance->setTranslator(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});

return $instance;
