<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'routing.loader' shared service.

$a = ${($_ = isset($this->services['file_locator']) ? $this->services['file_locator'] : $this->services['file_locator'] = new \Symfony\Component\HttpKernel\Config\FileLocator(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel')) && false ?: '_'}, ($this->targetDirs[2].'/app/Resources'), array(0 => ($this->targetDirs[2].'/app')))) && false ?: '_'};

$b = new \Symfony\Component\Config\Loader\LoaderResolver();
$b->addLoader(new \Symfony\Component\Routing\Loader\XmlFileLoader($a));
$b->addLoader(new \Symfony\Component\Routing\Loader\YamlFileLoader($a));
$b->addLoader(new \Symfony\Component\Routing\Loader\PhpFileLoader($a));
$b->addLoader(new \Symfony\Component\Routing\Loader\GlobFileLoader($a));
$b->addLoader(new \Symfony\Component\Routing\Loader\DirectoryLoader($a));
$b->addLoader(new \Symfony\Component\Routing\Loader\DependencyInjection\ServiceRouterLoader($this));

return $this->services['routing.loader'] = new \Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader(${($_ = isset($this->services['controller_name_converter']) ? $this->services['controller_name_converter'] : $this->services['controller_name_converter'] = new \Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel')) && false ?: '_'})) && false ?: '_'}, $b);
