<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.loader' shared service.

$this->services['twig.loader'] = $instance = new \Symfony\Bundle\TwigBundle\Loader\FilesystemLoader(${($_ = isset($this->services['templating.locator']) ? $this->services['templating.locator'] : $this->load('getTemplating_LocatorService.php')) && false ?: '_'}, ${($_ = isset($this->services['templating.name_parser']) ? $this->services['templating.name_parser'] : $this->services['templating.name_parser'] = new \Symfony\Bundle\FrameworkBundle\Templating\TemplateNameParser(${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel')) && false ?: '_'})) && false ?: '_'}, '/src');

$instance->addPath('/src/vendor/symfony/framework-bundle/Resources/views', 'Framework');
$instance->addPath('/src/vendor/symfony/framework-bundle/Resources/views', '!Framework');
$instance->addPath('/src/vendor/symfony/twig-bundle/Resources/views', 'Twig');
$instance->addPath('/src/vendor/symfony/twig-bundle/Resources/views', '!Twig');
$instance->addPath('/src/src/Resources/views', 'NorsysSeo');
$instance->addPath('/src/src/Resources/views', '!NorsysSeo');

return $instance;
